plugins:
  RagniGarg97/prow-test:
  - size
  - cat
  - dog
  - lgtm
  - trigger
  prow1/prow-test:
  - size
  - cat
  - dog
  - lgtm
  - trigger


triggers:
- repos:
  - prow1/prow-test
- repos:
  - RagniGarg97/prow-test

lgtm:
- repos:
  - prow1/prow-test
  - RagniGarg97/prow-test
  review_acts_as_lgtm: true

